services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    env_file: .env   # This loads the variables we created in user-data.sh
    volumes:
      - ./backend/resumes:/app/backend/resumes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - backend




